import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchAllFamilies } from './arxiv';
import { tagPaper } from './tag';
import type { TaggedCandidate } from './schema';
import { PAPERS } from '../src/data/papers';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

interface CliArgs {
  dry: boolean;
  from: string;
  max: number;
}

function parseArgs(): CliArgs {
  const args: CliArgs = {
    dry: false,
    from: defaultFromDate(),
    max: 120,
  };
  for (const a of process.argv.slice(2)) {
    if (a === '--dry') args.dry = true;
    else if (a.startsWith('--from=')) args.from = a.split('=')[1];
    else if (a.startsWith('--max=')) args.max = parseInt(a.split('=')[1], 10);
  }
  return args;
}

function defaultFromDate(): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - 60);
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}`;
}
function pad(n: number) {
  return String(n).padStart(2, '0');
}

function existingArxivIds(): Set<string> {
  const s = new Set<string>();
  for (const p of PAPERS) {
    if (!p.arxiv) continue;
    const m = p.arxiv.match(/abs\/([^\/?#v]+)/);
    if (m) s.add(m[1]);
  }
  return s;
}

async function main() {
  const args = parseArgs();
  console.log(`[crawl] from=${args.from} dry=${args.dry} max=${args.max}`);
  console.log(`[crawl] existing papers: ${PAPERS.length}`);

  const raw = await fetchAllFamilies({ fromDate: args.from, maxPerQuery: 80 });
  const known = existingArxivIds();
  const fresh = raw.filter((r) => !known.has(r.id));
  console.log(
    `[crawl] raw=${raw.length}  new=${fresh.length}  already-in-db=${raw.length - fresh.length}`,
  );

  const rawPath = path.join(ROOT, 'scripts', '.crawl-raw.json');
  fs.writeFileSync(rawPath, JSON.stringify(fresh, null, 2));
  console.log(`[crawl] wrote ${rawPath}`);

  if (args.dry) {
    const preview = fresh.slice(0, 20).map((p) => ({
      id: p.id,
      published: p.published.slice(0, 10),
      title: p.title.slice(0, 90),
    }));
    console.table(preview);
    console.log('[dry] exiting without tagging.');
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('[fatal] ANTHROPIC_API_KEY not set.');
    process.exit(2);
  }

  const pool = fresh.slice(0, args.max);
  console.log(`[tag] tagging ${pool.length} candidates…`);
  const tagged: TaggedCandidate[] = [];
  let rejected = 0;
  for (let i = 0; i < pool.length; i++) {
    const p = pool[i];
    try {
      const t = await tagPaper(p);
      if (!t) {
        rejected++;
        continue;
      }
      if (!t.is_avatar_paper) {
        rejected++;
        console.log(`  · skip (non-avatar): ${p.id} — ${t.reject_reason ?? ''}`);
        continue;
      }
      tagged.push(t);
      console.log(`  ✓ ${p.id}  ${t.id}  imp=${t.importance}`);
    } catch (err) {
      console.error(`  ✗ ${p.id}:`, (err as Error).message);
      rejected++;
    }
  }

  console.log(`[tag] accepted=${tagged.length}  rejected=${rejected}`);

  const out = renderCandidates(tagged);
  const outPath = path.join(ROOT, 'src', 'data', 'candidates.ts');
  fs.writeFileSync(outPath, out);
  console.log(`[write] ${outPath} (${tagged.length} entries)`);
}

function renderCandidates(tagged: TaggedCandidate[]): string {
  const entries = tagged
    .sort((a, b) => b.year - a.year || b.importance - a.importance)
    .map(renderEntry)
    .join(',\n');
  return `// generated by npm run crawl on ${new Date().toISOString()}
import type { Paper } from '../types';

export const CANDIDATES: Paper[] = [
${entries}
];
`;
}

function renderEntry(t: TaggedCandidate): string {
  const lines: string[] = [];
  lines.push(`  {`);
  lines.push(`    id: ${JSON.stringify(t.id)},`);
  lines.push(`    title: ${JSON.stringify(t.title)},`);
  lines.push(`    authors: ${JSON.stringify(t.authors)},`);
  lines.push(`    year: ${t.year},`);
  lines.push(`    venue: ${JSON.stringify(t.venue)},`);
  lines.push(`    tier: ${t.tier},`);
  lines.push(`    importance: ${t.importance},`);
  if (t.arxiv) lines.push(`    arxiv: ${JSON.stringify(t.arxiv)},`);
  lines.push(`    summary: ${JSON.stringify(t.summary)},`);
  lines.push(`    contribution: ${JSON.stringify(t.contribution)},`);
  lines.push(`    representation: ${JSON.stringify(t.representation)},`);
  lines.push(`    input: ${JSON.stringify(t.input)},`);
  lines.push(`    pipeline: ${JSON.stringify(t.pipeline)},`);
  lines.push(`    capability: ${JSON.stringify(t.capability)},`);
  lines.push(`    target: ${JSON.stringify(t.target)},`);
  lines.push(`  }`);
  return lines.join('\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
